device: /dev/ttyACM0
frame_id: gps
uart1:
  baudrate: 38400
config_on_startup: false

# Enable u-blox message publishers
publish:
  all: false
  nav:
    all: true
    relposned: true
    posllh: true
    posecef: true
  nmea: true
